include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "packages/azure_speech/test/**"
    - "packages/ffmpeg_kit_flutter_new/**"
  errors:
    avoid_print: error

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_build_context_synchronously: true
